name: rle
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  animated_text_kit: ^3.1.2
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  modal_progress_hud: ^0.1.3
  google_sign_in: ^4.5.9
  image_picker: ^0.6.7+22
  path_provider: ^1.6.27
  image: ^2.1.19
  uuid: ^2.2.2
  firebase_storage: ^7.0.0
  algolia: ^0.1.7
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

